server:
  port: 8000
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: SCW-PROJECT
  redis:
    host: 192.168.188.130
    port: 6379
    password: 123456
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/project/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: baiboli.oss-cn-beijing.aliyuncs.com
  accessKeyId: xxxxx
  accessKeySecret: xxxxx
  bucketName: baiboli


